# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 14:39
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grain', '0006_auto_20160918_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrainEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('creation', 'Create'), ('update', 'Edit'), ('deletion', 'Delete')], max_length=20)),
                ('model', models.CharField(max_length=30)),
                ('object_pk', models.IntegerField()),
                ('time', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
