# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grain', '0007_grainevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='method',
            field=models.CharField(choices=[('frying', 'Fried'), ('boiling', 'Boiled'), ('poaching', 'Poached'), ('baking', 'Baked'), ('roasting', 'Roasted'), ('uncooked', 'Uncooked'), ('instant', 'Microwaved')], max_length=8),
        ),
    ]
